#!/usr/bin/env sh
exec poke -L "$0" "$@"
!#

load "applersrc.pk";

var filename = argv[0];

var file = open(filename, IOS_M_RDONLY);

var rsrc = RsrcHeader @ file : 0#B;
var map = RsrcMap @ rsrc.map_offset;
var type_list = RsrcList @ rsrc.map_offset + map.type_list_offset;

for (rsrc_type in type_list.types) {
  printf "%s\n", string @ rsrc_type.rsrc_type.data'offset;
}

// vim: ft=poke :
