#!/usr/bin/env sh
exec poke -L "$0" "$@"
!#

load appleutils;

var filename = argv[0];

var file = open(filename, IOS_M_RDONLY);

var rsrc = rsrcfork(file);

for (rsrc_type in rsrc.types.types) {
  printf "%s\n", rsrc_type.rsrc_type_name;
}

// vim: ft=poke :
